### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fallaciousreasoning** [fallaciousreasoning/topo#2]
- [ ] Settings
    - [ ] Appearance
    - [ ] Layers
    - [ ] Caching
- Tracks
    - [ ] Create track
    - [ ] Edit track
    - [ ] Import track from url
    - [ ] Create track from file
    - [ ] Export track
    - [ ] Manage existing tracks
    - [ ] View track(s)
- Waypoints
    - [ ] Create/Edit/View track
    - [ ] Export
    - [ ] Share
    - [ ] Manage existing
- [ ] Backup to cloud drive
