### ISSUE TITLE
MapLibre / React Alpha

### ISSUE THREAD

**Issue by fallaciousreasoning** [fallaciousreasoning/topo#22]
## TODO for Release
- [ ] track creation / editing
- [ ] offline storage / layer options
- [ ] scroller / filter for mountains / routes
